[assembly: System.Reflection.AssemblyTitle("VMDL")]
[assembly: System.Reflection.AssemblyDescription("Virtual Machine Deployment Launcher")]
[assembly: System.Reflection.AssemblyCompany("RandomiaGaming")]
[assembly: System.Reflection.AssemblyProduct("VMDL")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © RandomiaGaming 2022")]
[assembly: System.Reflection.AssemblyTrademark("Trademark ™ RandomiaGaming 2022")]
[assembly: System.Reflection.AssemblyCulture("")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]